name: Continuous Integration

on: pull_request

jobs:
  ci:
    runs-on: windows-2022

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore ./FinTrack/Backend/Backend.csproj
        working-directory: ./FinTrack
        
      - name: Compilar o projeto
        run: dotnet build ./FinTrack/Backend/Backend.csproj --configuration Release --no-restore
        working-directory: ./FinTrack

      - name: Executar testes
        run: dotnet test ./FinTrack/Backend/Backend.csproj --no-build --verbosity normal
        working-directory: ./FinTrack
